spring.application.name=karvachauth

spring.profiles.active=dev
server.port=${PORT:8086}


karix.waba.number=917795618702
karix.api.url=https://rcmapi.instaalerts.zone/services/rcm/sendMessage
karix.api.key=qeaEYqrIQY5cIvbjVEGJ2A==